<a href="https://colab.research.google.com/github/thunerous/NM/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import statistics

Створи матрицю 3*3, заповни її цілими випадковими числами від 1 до 5

In [2]:
np.random.seed(42)
matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[4, 5, 3],
       [5, 5, 2],
       [3, 3, 3]])

Обчислити визначник матриці

In [3]:
det = np.linalg.det(matrix)
det

np.float64(-9.000000000000002)

Знайти добуток всіх елементів матриці

In [4]:
product = np.prod(matrix)
product

np.int64(81000)

Знайти суму всіх елементів матриці

In [5]:
total_sum = np.sum(matrix)
total_sum

np.int64(33)

Обчислити найбільший, найменший елементи

In [6]:
max_val = np.max(matrix)
min_val = np.min(matrix)
print(f"Max: {max_val}, Min: {min_val}")

Max: 5, Min: 2


Знайти середнє значення елементів матриці

In [7]:
average = np.mean(matrix)
average

np.float64(3.6666666666666665)

Знайти матрицю, що складена з квадратних коренів

In [8]:
sqrt_matrix = np.sqrt(matrix)
sqrt_matrix

array([[2.        , 2.23606798, 1.73205081],
       [2.23606798, 2.23606798, 1.41421356],
       [1.73205081, 1.73205081, 1.73205081]])

Обчислити суму елементів кожного рядка. Відповідь записати як вектор-стовпчик

In [9]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)
row_sums

array([[12],
       [12],
       [ 9]])

Створити вектор, що містить 25 елементів. Заповнити числами від 0 до 9. Відсортувати числа за спаданням

In [10]:
vector = np.random.randint(0, 10, size=25)
sorted_vector = np.sort(vector)[::-1]
sorted_vector

array([9, 9, 8, 8, 7, 7, 7, 7, 6, 5, 5, 5, 4, 4, 4, 4, 3, 3, 2, 2, 2, 1,
       1, 0, 0])

Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [13]:
print(f"мода: {statistics.mode(vector)}")
print(f"медіана: {np.median(vector)}")
print(f"середнє: {np.mean(vector)}")
print(f"максимальне: {np.max(vector)}")
print(f"мінімальне: {np.min(vector)}")

мода: 7
медіана: 4.0
середнє: 4.52
максимальне: 9
мінімальне: 0


Створити дві матриці 4*4, заповнені числами від 1 до 10. Обчислити суму, різницю, поелементний добуток, частку

In [15]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

print("\nСума:")
print(matrix1 + matrix2)

print("\nРізниця:")
print(matrix1 - matrix2)

print("\nПоелементний добуток:")
print(matrix1 * matrix2)

print("\nЧастка:")
print(matrix1 / matrix2)

Матриця 1:
[[10  4  8  7]
 [ 9  8  5  2]
 [ 5  8 10  9]
 [ 9  1  9  7]]

Матриця 2:
[[ 9  8  1  8]
 [ 8  3  1  8]
 [ 3  3  1  5]
 [10  7 10  9]]

Сума:
[[19 12  9 15]
 [17 11  6 10]
 [ 8 11 11 14]
 [19  8 19 16]]

Різниця:
[[ 1 -4  7 -1]
 [ 1  5  4 -6]
 [ 2  5  9  4]
 [-1 -6 -1 -2]]

Поелементний добуток:
[[90 32  8 56]
 [72 24  5 16]
 [15 24 10 45]
 [90  7 90 63]]

Частка:
[[ 1.11111111  0.5         8.          0.875     ]
 [ 1.125       2.66666667  5.          0.25      ]
 [ 1.66666667  2.66666667 10.          1.8       ]
 [ 0.9         0.14285714  0.9         0.77777778]]


Задати вектор-рядок, що містить дійсні числа 1.0-8.0. Зробити матрицю 3*3.Помножити на вектор-рядок, що містить числа 1.0-2.0

In [16]:
row_vector = np.linspace(1.0, 8.0, 9).reshape(3, 3)
mult_vector = np.linspace(1.0, 2.0, 3)
result = row_vector * mult_vector
print("Оригінальна матриця:")
print(row_vector)
print("\nВектор:")
print(mult_vector)
print("\nРезультат:")
print(result)

Оригінальна матриця:
[[1.    1.875 2.75 ]
 [3.625 4.5   5.375]
 [6.25  7.125 8.   ]]

Вектор:
[1.  1.5 2. ]

Результат:
[[ 1.      2.8125  5.5   ]
 [ 3.625   6.75   10.75  ]
 [ 6.25   10.6875 16.    ]]


Задати вектор-рядок (числа 1-5). Обчислити вектор в кубі.

In [17]:
vector = np.array([1, 2, 3, 4, 5])
cubed_vector = vector ** 3
print("Оригінал:", vector)
print("В кубі:", cubed_vector)

Оригінал: [1 2 3 4 5]
В кубі: [  1   8  27  64 125]


Висновок

---


Навчився обчислювати різноманітні операції над матрицями за допомогою бібліотеки NumPy
